export const TEAM_LOGOS: Record<string, string> = {
  'MI': 'https://bkt-sports-prod.s3.amazonaws.com/teams/mi.png',
  'MUMBAI': 'https://bkt-sports-prod.s3.amazonaws.com/teams/mi.png',
  'MUMBAI INDIANS': 'https://bkt-sports-prod.s3.amazonaws.com/teams/mi.png',
  'MUMBAI INDIANS (MI)': 'https://bkt-sports-prod.s3.amazonaws.com/teams/mi.png',
  'CSK': 'https://bkt-sports-prod.s3.amazonaws.com/teams/csk.png',
  'CHENNAI': 'https://bkt-sports-prod.s3.amazonaws.com/teams/csk.png',
  'CHENNAI SUPER KINGS': 'https://bkt-sports-prod.s3.amazonaws.com/teams/csk.png',
  'CHENNAI SUPER KINGS (CSK)': 'https://bkt-sports-prod.s3.amazonaws.com/teams/csk.png',
  'RCB': 'https://bkt-sports-prod.s3.amazonaws.com/teams/rcb.png',
  'BANGALORE': 'https://bkt-sports-prod.s3.amazonaws.com/teams/rcb.png',
  'BENGALURU': 'https://bkt-sports-prod.s3.amazonaws.com/teams/rcb.png',
  'ROYAL CHALLENGERS BENGALURU': 'https://bkt-sports-prod.s3.amazonaws.com/teams/rcb.png',
  'ROYAL CHALLENGERS BANGALORE': 'https://bkt-sports-prod.s3.amazonaws.com/teams/rcb.png',
  'ROYAL CHALLENGERS BENGALURU (RCB)': 'https://bkt-sports-prod.s3.amazonaws.com/teams/rcb.png',
  'KKR': 'https://bkt-sports-prod.s3.amazonaws.com/teams/kkr.png',
  'KOLKATA': 'https://bkt-sports-prod.s3.amazonaws.com/teams/kkr.png',
  'KOLKATA KNIGHT RIDERS': 'https://bkt-sports-prod.s3.amazonaws.com/teams/kkr.png',
  'KOLKATA KNIGHT RIDERS (KKR)': 'https://bkt-sports-prod.s3.amazonaws.com/teams/kkr.png',
  'GT': 'https://bkt-sports-prod.s3.amazonaws.com/teams/gt.png',
  'GUJARAT': 'https://bkt-sports-prod.s3.amazonaws.com/teams/gt.png',
  'GUJARAT TITANS': 'https://bkt-sports-prod.s3.amazonaws.com/teams/gt.png',
  'GUJARAT TITANS (GT)': 'https://bkt-sports-prod.s3.amazonaws.com/teams/gt.png',
  'RR': 'https://bkt-sports-prod.s3.amazonaws.com/teams/rr.png',
  'RAJASTHAN': 'https://bkt-sports-prod.s3.amazonaws.com/teams/rr.png',
  'RAJASTHAN ROYALS': 'https://bkt-sports-prod.s3.amazonaws.com/teams/rr.png',
  'RAJASTHAN ROYALS (RR)': 'https://bkt-sports-prod.s3.amazonaws.com/teams/rr.png',
  'LSG': 'https://bkt-sports-prod.s3.amazonaws.com/teams/lsg.png',
  'LUCKNOW': 'https://bkt-sports-prod.s3.amazonaws.com/teams/lsg.png',
  'LUCKNOW SUPER GIANTS': 'https://bkt-sports-prod.s3.amazonaws.com/teams/lsg.png',
  'LUCKNOW SUPER GIANTS (LSG)': 'https://bkt-sports-prod.s3.amazonaws.com/teams/lsg.png',
  'PBKS': 'https://bkt-sports-prod.s3.amazonaws.com/teams/pbks.png',
  'PUNJAB': 'https://bkt-sports-prod.s3.amazonaws.com/teams/pbks.png',
  'PUNJAB KINGS': 'https://bkt-sports-prod.s3.amazonaws.com/teams/pbks.png',
  'PUNJAB KINGS (PBKS)': 'https://bkt-sports-prod.s3.amazonaws.com/teams/pbks.png',
  'DC': 'https://bkt-sports-prod.s3.amazonaws.com/teams/dc.png',
  'DELHI': 'https://bkt-sports-prod.s3.amazonaws.com/teams/dc.png',
  'DELHI CAPITALS': 'https://bkt-sports-prod.s3.amazonaws.com/teams/dc.png',
  'DELHI CAPITALS (DC)': 'https://bkt-sports-prod.s3.amazonaws.com/teams/dc.png',
  'SRH': 'https://bkt-sports-prod.s3.amazonaws.com/teams/srh.png',
  'HYDERABAD': 'https://bkt-sports-prod.s3.amazonaws.com/teams/srh.png',
  'SUNRISERS HYDERABAD': 'https://bkt-sports-prod.s3.amazonaws.com/teams/srh.png',
  'SUNRISERS HYDERABAD (SRH)': 'https://bkt-sports-prod.s3.amazonaws.com/teams/srh.png',
};
